/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Public } from "../../decorators/public.decorator";
import { DeleteBierArgs } from "./DeleteBierArgs";
import { BierFindManyArgs } from "./BierFindManyArgs";
import { BierFindUniqueArgs } from "./BierFindUniqueArgs";
import { Bier } from "./Bier";
import { BierService } from "../bier.service";

@graphql.Resolver(() => Bier)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class BierResolverBase {
  constructor(
    protected readonly service: BierService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @graphql.Query(() => MetaQueryPayload)
  async _biersMeta(
    @graphql.Args() args: BierFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @Public()
  @graphql.Query(() => [Bier])
  async biers(@graphql.Args() args: BierFindManyArgs): Promise<Bier[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Bier, { nullable: true })
  async bier(@graphql.Args() args: BierFindUniqueArgs): Promise<Bier | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Bier)
  @nestAccessControl.UseRoles({
    resource: "Bier",
    action: "delete",
    possession: "any",
  })
  async deleteBier(@graphql.Args() args: DeleteBierArgs): Promise<Bier | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
